# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'faker'

User.destroy_all
Review.destroy_all
Park.destroy_all


Park.find_or_create_by(name:"Little River Canyon", state: "Alabama, AL", description: "Little River is unique because it flows for most of its length atop Lookout Mountain in northeast Alabama. Forested uplands, waterfalls, canyon rims and bluffs, pools, boulders, and sandstone cliffs offer settings for a variety of recreational activities. Natural resources and cultural heritage come together to tell the story of the Preserve, a special place in the Southern Appalachians.", amenity: "Parking")
Park.find_or_create_by(name:"Denali Park", state: "Alaska, AK", description: "Denali is six million acres of wild land, bisected by one ribbon of road. Travelers along it see the relatively low-elevation taiga forest give way to high alpine tundra and snowy mountains, culminating in North America's tallest peak, 20,310 \' Denali. Wild animals large and small roam un-fenced lands, living as they have for ages. Solitude, tranquility and wilderness await.", amenity: "Parking")
Park.find_or_create_by(name:"Grand Canyon", state: "Arizona, AZ", description: "Located in Arizona, Grand Canyon National Park encompasses 277 miles (446 km) of the Colorado River and adjacent uplands. The park is home to much of the immense Grand Canyon; a mile (1.6 km) deep, and up to 18 miles (29 km) wide. Layered bands of colorful rock reveal millions of years of geologic history. Grand Canyon is unmatched in the incomparable vistas it offers visitors from the rim.", amenity: "Parking")
Park.find_or_create_by(name:"Hot Springs", state: "Arkansas, AR", description: "Hot Springs National Park has a rich cultural past. The grand architecture of our historic bathhouses is equally matched by the natural curiosities that have been drawing people here for hundreds of years. Ancient thermal springs, mountain views, incredible geology, forested hikes, and abundant creeks – all in the middle of town – make Hot Springs National Park a unique and beautiful destination.", amenity: "Parking")
Park.find_or_create_by(name:"Joshua Tree", state: "California, CA", description: "Two distinct desert ecosystems, the Mojave and the Colorado, come together in Joshua Tree National Park. A fascinating variety of plants and animals make their homes in a land sculpted by strong winds and occasional torrents of rain. Dark night skies, a rich cultural history, and surreal geologic features add to the wonder of this vast wilderness in southern California. Come explore for yourself.", amenity: "Parking")
Park.find_or_create_by(name:"Black Canyon Of The Gunnison", state: "Colorado, CO", description: "Big enough to be overwhelming, still intimate enough to feel the pulse of time, Black Canyon of the Gunnison exposes you to some of the steepest cliffs, oldest rock, and craggiest spires in North America. With two million years to work, the Gunnison River, along with the forces of weathering, has sculpted this vertical wilderness of rock, water, and sky.", amenity: "Parking")
Park.find_or_create_by(name:"Everglades", state: "Florida, FL", description: "Everglades National Park protects an unparalleled landscape that provides important habitat for numerous rare and endangered species like the manatee, American crocodile, and the elusive Florida panther. An international treasure as well - a World Heritage Site, International Biosphere Reserve, a Wetland of International Importance, and a specially protected area under the Cartagena Treaty.", amenity: "Parking")
Park.find_or_create_by(name:"Chickamauga & Chattanooga", state: "Georgia, GA", description: "In 1863, Union and Confederate forces fought for control of Chattanooga, known as the \"Gateway to the Deep South.\" The Confederates were victorious at nearby Chickamauga in September. However, renewed fighting in Chattanooga that November provided Union troops victory and control of the city. After the fighting, a Confederate soldier ominously wrote, \"This...is the death-knell of the Confederacy.\" ", amenity: "Parking")
Park.find_or_create_by(name:"Hawai\'i Volcanoes", state: "Hawaii, HI", description: "Although not yet open to the public, Honouliuli National Historic Site will tell the history of internment, martial law, and the experience of prisoners of war in Hawai‘i during World War II. Honouliuli National Historic Site will be a place to reflect on wartime experiences and recommit ourselves to the pursuit of freedom and justice.", amenity: "Parking")
Park.find_or_create_by(name:"Yellowstone", state: "Idaho, ID", description: "On March 1, 1872, Yellowstone became the first national park for all to enjoy the unique hydrothermal and geologic wonders. Theses wonders were captured a year earlier in the art of William Henry Jackson’s photographs, Thomas Moran\’s paintings, and Henry Elliot\’s sketches during the 1871 Hayden Expedition. Their work inspired Congress to preserve the area.", amenity: "Parking")
Park.find_or_create_by(name:"Tallgrass Prairie", state: "Kansas, KS", description: "Tallgrass prairie once covered 170 million acres of North America, but within a generation most of it had been transformed into farmland. Today less than 4% remains intact, mostly in the Kansas Flint Hills. Established on November 12, 1996, the preserve protects a nationally significant remnant of the once vast tallgrass prairie ecosystem. Here the tallgrass makes its last stand.", amenity: "Parking")
Park.find_or_create_by(name:"Mammoth Cave", state: "Kentucky, KY", description: "Rolling hills, deep river valleys, and the worlds longest known cave system. Mammoth Cave National Park is home to thousands of years of human history and a rich diversity of plant and animal life, earning it the title of UNESCO World Heritage Site and International Biosphere Reserve.", amenity: "Parking")
Park.find_or_create_by(name:"Acadia", state: "Maine, ME", description: "Acadia National Park protects the natural beauty of the highest rocky headlands along the Atlantic coastline of the United States, an abundance of habitats, and a rich cultural heritage. At 3.5 million visits a year, it\'s one of the top 10 most-visited national parks in the United States. Visitors enjoy 27 miles of historic motor roads, 158 miles of hiking trails, and 45 miles of carriage roads.", amenity: "Parking")
Park.find_or_create_by(name:"Assateague Island", state: "Maryland, MD", description: "Want to live on the edge? Visit a place recreated each day by ocean wind and waves. Life on Assateague Island has adapted to an existence on the move. Explore sandy beaches, salt marshes, maritime forests and coastal bays. Rest, relax, recreate and enjoy some time on the edge of the continent.", amenity: "Parking")
Park.find_or_create_by(name:"Isle Royale", state: "Michigan, MI", description: "Explore a rugged, isolated island, far from the sights and sounds of civilization. Surrounded by Lake Superior, Isle Royale offers unparalleled solitude and adventures for backpackers, hikers, boaters, kayakers, canoeists and scuba divers. Here, amid stunning scenic beauty, you'll find opportunities for reflection and discovery, and make memories that last a lifetime.", amenity: "Parking")
